"use client";
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { useEffect, useState } from 'react'


// export const metadata = {
//   title: 'Next.js Tutorial',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [topics, setTopics] = useState([]);
  useEffect(() => {
    fetch('http://localhost:9999/topics')
    .then(res => res.json())
    .then(result => {
      console.log(result);
      setTopics(result);
    })
  }, []);
  return (
    <html >
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {/* <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li> */}
          {topics.map((topic) => {
                return (<li key={topic.id}>
                 <Link href={`/read/${topic.id}`}>{topic.title}</Link>
               </li>)
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete"></input></li>
        </ul>
      </body>
    </html>
  )
}
