import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { Control } from './Control';


export const metadata = {
  title: 'Next.js Tutorial',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // 비효율적인 방식 {cache: 'no-store'} 캐시를 저장하지 않겠다.
  console.log('process', process.env.API_URL);
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics`, {cache: 'no-store'});
  const topics = await res.json();
  
  return (
    <html >
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {/* <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li> */}
          {topics.map((topic) => {
                return (<li key={topic.id}>
                 <Link href={`/read/${topic.id}`}>{topic.title}</Link>
               </li>)
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
